[package]
name = "quantum_encryptor"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
aes = "0.8.4"
hex = "0.4.3"

[profile.release]
panic = "abort"
debug = 0
debug-assertions = false
opt-level = 3
codegen-units = 1
lto = true
